many many changes

diff --git a/dotfiles/.local/bin/statusbar/news b/dotfiles/.local/bin/statusbar/news
--- a/dotfiles/.local/bin/statusbar/news
+++ b/dotfiles/.local/bin/statusbar/news
@@ -15,9 +15,7 @@ case $BLOCK_BUTTON in
 <b>Note:</b> Only one instance of newsboat (including updates) may be running at a time." ;;
 esac
 
-NEWNEWS=$(cat ~/.config/newsboat/.update 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)")
+NEWSUPD=$(newsboat -x print-unread | awk '$1 ~ /^[0-9]+$/ { if($1>0) print " " $1}' || echo "error")
+[ $NEWSUPD != "error" ] || echo $NEWSUPD > /tmp/.newsupdate
 
-if [ ! -x $NEWNEWS ]; then
-    echo  $NEWNEWS
-fi
-
+cat /tmp/.newsupdate 2> /dev/null 
